name: Node.js CI

on: 
  push:
    branches:
      - 'releases/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          always-auth: true
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: yarn lint
      - run: yarn build-package
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN}}
